export NEO=/mnt/ssd/neo4j-enterprise-3.1.4

$NEO/bin/neo4j-import --into /mnt/ssd/tranfers.db --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 30000000 --nodes:Transaction transaction.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 30000000 --nodes:Transaction transaction.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 30000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --nodes:Account account.hdr,`echo account*.csv.gz | tr ' ' ','` --relationships:SENDER sender.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --relationships:RECEIVER receiver.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 30000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --nodes:Account account.hdr,`echo account*.csv.gz | tr ' ' ','` --relationships:SENDER sender.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --relationships:RECEIVER receiver.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 30000000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [123]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [123]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [123]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [123]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [123]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [12]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [12]-file-*.csv.gz | tr ' ' ','`
$NEO/bin/neo4j-import --into $DB --stacktrace true --skip-duplicate-nodes true   --skip-bad-relationships true  --ignore-empty-strings true --bad-tolerance 2100000000 --id-type string --db-config neo4j.conf --ignore-extra-columns true --skip-bad-entries-logging true --nodes:Transaction transaction.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --nodes:Account account.hdr,`echo account-[0-3]*.csv.gz | tr ' ' ','` --relationships:SENDER sender.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','` --relationships:RECEIVER receiver.hdr,`echo [1]-file-1*.csv.gz | tr ' ' ','`